version: "3.10"

services:
  app:
    build:
      context: ./app
    container_name: knowledge_graph_app
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=Test1234
    command: python app.py

  neo4j:
    image: neo4j:5.9.0
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/your_password

volumes:
  neo4j_data:
  neo4j_logs:
